apiVersion: batch/v1
kind: Job
metadata:
  name: model-download
  namespace: default
spec:
  backoffLimit: 3
  template:
    metadata:
      labels:
        app: model-download
    spec:
      restartPolicy: OnFailure
      containers:
      - name: download
        image: public.ecr.aws/parikshit/huggingface-cli:slim
        command:
        - hf
        - download
        - "Hello2pariksit/Mistral-7B-Instruct-v0.3-neuron"
        - "--local-dir"
        - "/work-dir/Mistral-7B-Instruct-v0.3"
        env:
          - name: HF_TOKEN
            valueFrom:
              secretKeyRef:
                name: hf-token
                key: token
                optional: true
        resources:
          requests:
            memory: 2Gi
          limits:
            memory: 8Gi
        volumeMounts:
        - name: persistent-storage
          mountPath: "/work-dir"
      volumes:
      - name: persistent-storage
        persistentVolumeClaim:
          claimName: ontap-model-claim
