apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ontap-model-claim
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ontap-nas-sc
  resources:
    requests:
      storage: 100Gi
