apiVersion: v1
kind: ConfigMap
metadata:
  name: litellm-config
  namespace: default
data:
  config.yaml: |
    model_list:
      - model_name: "workshop-llm"
        litellm_params:
          model: "openai/mistral-7b-neuron"
          api_base: "http://vllm-mistral7b-service.default.svc.cluster.local/v1"
          api_key: "not-needed"

      - model_name: "workshop-llm-tools"
        litellm_params:
          model: "bedrock/us.anthropic.claude-haiku-4-5-20251001-v1:0"
