kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: itops-agent-data-pvc
  annotations:
    trident.netapp.io/importVolume: "itops_agent_data"
    trident.netapp.io/importBackend: "fsx-ontap-nas"
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ontap-nas-sc
  resources:
    requests:
      storage: 10Gi
