apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: finance-data-claim
  namespace: model-finance
spec:
  accessModes:
    - ReadOnlyMany
  storageClassName: ontap-nas-segregated
  resources:
    requests:
      storage: 50Gi
  selector:
    matchLabels:
      data-domain: finance
