apiVersion: v1
kind: PersistentVolume
metadata:
  name: finance-data-pv
  labels:
    data-domain: finance
spec:
  capacity:
    storage: 50Gi
  accessModes:
    - ReadOnlyMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ontap-nas-segregated
  mountOptions:
    - nfsvers=4.1
    - hard
    - rsize=65536
    - wsize=65536
  nfs:
    server: CLOUD_NFS_LIF_IP
    path: /finance_data
  claimRef:
    namespace: model-finance
    name: finance-data-claim
